package:
  name: vounwarp
  version: "1.1"

source:
  url: https://github.com/nghia-vo/vounwarp/archive/v1.1.tar.gz
  sha256: e22195467c2c72a3017a0a8fc759840c0ec9361908cd39872b729d0f0cef8a46
build:
  number: 0
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy 
    - scipy
    - scikit-image
    - pillow
    - matplotlib
    - h5py
test:
  imports:
    - vounwarp   

about:
  home: https://github.com/nghia-vo/vounwarp
  license:  Apache 2.0
  license_file: LICENSE
  summary: 'Distortion correction for tomography. https://doi.org/10.1364/OE.23.032859 '

extra:
  recipe-maintainers:
    - nghia-vo
