travis:
  secure:
    BINSTAR_TOKEN: JIyDj7bHN/3o5x4bXQlm5b7XsYQcHsTArhDk5auJiybLVh3+kl/KSY0s9UjtZXkmLDa9YnzKZnGsq+phXgPBDjZ2IZ4LGUxJg6DHq7WwrY3j8X68+O98iEG1lYejZd30YA0PedUQqU10RmAF3kymZnQmgNlhsIeza6I9Cm3+5x93QtmzSjv11HC9k2vAX9WVQNR8oRVBjk1k2fuHiaYdsRNmwc7L9TQtrcQMqDzufpbmvAzQf3EEe00VtdbNyGngf5eQINJJYMw3+CtpSm+eHoknT6JTS8/ejL4gfyjicdtTHTSZdpaduQAavWTWOMkVZs+MGzsA7j8EzAAeHHjmyz35qfAgzoEH9HxJJh/vCK4shRJPS7rgN03jgT3xFoc3YdZxTENt5OBh7QMYm2/chDF/3Eq5BAN80AaYgDPULWFpihzYYYcRLpg6Q3q9CO+A3vWKhQ85IheMv08UaKEHBnlxDrhGGUYLtGAKuWjGn2dJp7nr6FwCt+0GrfxnsHY+WBLhN2bqEj8ZORIzMnmrr3pMtUjylv7AwGtYY6CiphW1N8UPFSvfiu9i3IXjRxMNH2nb+uoWSrPUncaHh3fgr7hKIQjIvS7AFw5oRviPPIj+80sw6ZqIhPc8k36XnDDxL6h6WwNYRsW9xqHEVZrfQpE8+zxpfw5C5S5UfceoKS0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
